# Generated by Django 6.0 on 2025-12-10 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_cpf_alter_userprofile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(help_text='Distância em quilômetros (km)')),
                ('tempo', models.DurationField(help_text='Tempo total da sessão')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('rota_gps', models.JSONField(blank=True, default=dict, help_text='Dados da rota GPS em formato JSON')),
                ('calorias_queimadas', models.FloatField(blank=True, help_text='Calorias estimadas queimadas', null=True)),
                ('velocidade_media', models.FloatField(blank=True, help_text='Velocidade média em km/h', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_cardio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Cardio',
                'verbose_name_plural': 'Sessões de Cardio',
                'ordering': ['-data_hora'],
            },
        ),
    ]
