# Generated by Django 6.0 on 2025-12-10 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cardio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardio',
            options={'ordering': ['-data_hora']},
        ),
        migrations.AlterField(
            model_name='cardio',
            name='calorias_queimadas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardio',
            name='distancia',
            field=models.FloatField(help_text='Distância em km'),
        ),
        migrations.AlterField(
            model_name='cardio',
            name='rota_gps',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cardio',
            name='tempo',
            field=models.DurationField(help_text='Tempo total'),
        ),
        migrations.AlterField(
            model_name='cardio',
            name='velocidade_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Instruções')),
                ('tipo_movimento', models.CharField(choices=[('EMPURRAR', 'Empurrar'), ('PUXAR', 'Puxar'), ('INFERIOR', 'Inferior (Pernas)'), ('CORE', 'Core'), ('MOBILIDADE', 'Mobilidade/Aquecimento')], default='EMPURRAR', max_length=20)),
                ('nivel_dificuldade', models.CharField(choices=[('INICIANTE', 'Iniciante'), ('INTERMEDIARIO', 'Intermediário'), ('AVANCADO', 'Avançado'), ('EXPERT', 'Expert')], default='INICIANTE', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (Customizado)')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Catálogo de Exercícios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Ficha')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default=3)),
                ('repetitions', models.CharField(blank=True, max_length=50, null=True)),
                ('tempo_segundos', models.IntegerField(default=0)),
                ('peso_adicional_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('order', models.IntegerField(default=0)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.exercicio')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ficha')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
