# Generated by Django 6.0 on 2025-12-10 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cardio_options_alter_cardio_calorias_queimadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='altura',
            field=models.FloatField(blank=True, help_text='Altura em cm', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso em kg', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
